---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-conf-pvc
  namespace: gitlab
spec:
  selector:
    matchLabels:
      name: gitlab-conf-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: gitlab
spec:
  selector:
    matchLabels:
      name: gitlab-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
  namespace: gitlab
spec:
  selector:
    matchLabels:
      name: gitlab-logs-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

