---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ee
        #        env:
                #          - name: GITLAB_OMNIBUS_CONFIG
            #            value: "external_url 'http://gitlab-service.default/';gitlab_rails['registry_enabled'] = true;gitlab_rails['registry_api_url'] = \"http://172.17.0.2:5000\""
        imagePullPolicy: Always
        ports:
          - name: http-port
            containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 2Gi
        volumeMounts:
          - name: gitlab
            mountPath: /var/opt/gitlab

      volumes:
        - name: gitlab
          persistentVolumeClain:
            claimName: gitlab-pvc
