---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: gitlab-svc
spec:
  selector:
    app: gitlab
  ports:
    - name: http-port
      protocol: TCP
      port: 8002
      targetPort: 80
