---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-conf-pv
  labels:
    name: gitlab-conf-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 1.2.4.5 # NFS server IP
    path: /k3s/gitlab/etc # path on nfs server for container storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
  labels:
    name: gitlab-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 1.2.3.4 # NFS server IP
    path: /k3s/gitlab/data # path on nfs server for container storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
  labels:
    name: gitlab-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 1.2.3.4 # NFS server IP
    path: /k3s/gitlab/logs # path on nfs server for container storage
